name: prepare-server

on: workflow_dispatch

# environments
# "PRODUCTION" | "PRERELEASE" | "DEVELOP"

env:
  HOST_USER: "ubuntu"
  APP_DIR_BE: "/home/ubuntu/fin-tracker/be"
  APP_DIR_FE: "/home/ubuntu/fin-tracker/fe"
  ARTIFACTS_DIR: "/home/ubuntu/fin-tracker/artifacts"
  NETWORK_NAME: "fin-tracker-network"

# secrets
# - REMOTE_HOST
# - SSH_KEY
# - SSH_PASSWORD
# - ENV_FILE

jobs:
  prepare-server:
    environment: PRODUCTION
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ env.HOST_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ${{ env.APP_DIR_BE }}
            mkdir -p ${{ env.APP_DIR_FE }}
            mkdir -p ${{ env.ARTIFACTS_DIR }}

            docker network create ${{ env.NETWORK_NAME }} || true

            cd ${{ env.APP_DIR_BE }}
            echo "${{ secrets.ENV_FILE }}" > ${{ env.APP_DIR_BE }}/.env
            chmod 600 ${{ env.APP_DIR_BE }}/.env
